name: "PAYCOM LABOR REPORT NIGHTLY REFRESH"

on:
  schedule:
  - cron: "45 13,14 * * 0-6"
  
  workflow_dispatch:
  
jobs:
  run-updater:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps: 
    - name: REST API with curl on schedule
      if: github.event_name == 'schedule'
      run: |
        if [ $(TZ="America/Los_Angeles" date +%H) -eq '6' ]; then
            curl --request POST \
            --url https://app.coalescesoftware.io/scheduler/startRun \
            --header 'Authorization: Bearer AMf-vBwtq_HISM5lWO0ZrsjpZJUP8ZZyi6_ZvlW0TSJ1fP_B9G4gxJYedW1Dqn-BXWemry4R7U3Dz3898XP49_LhIW8Qky1FOx2w9N9klXHvKNxFO9VzXUPmuKR1GMCHg9rZEd2JisZjOUxJp0mDWbwha8EEqw6B9sPq_QxOxNKVGne7WOBMGsbZkKlkTTupvPmTcxmOZGaR6i3NE2-Y0TF0Y6ua_d_j6Q' \
            --header 'accept: application/json' \
            --header 'content-type: application/json' \
            --data '
              {
                "runDetails": {
                  "parallelism": 16,
                  "environmentID": "7"
                },
                "userCredentials": {
                  "snowflakeAuthType": "Basic",
                  "snowflakeUsername": "DEEPAK2899",
                  "snowflakePassword": "DaDa2802#",
                  "snowflakeWarehouse": "COMPUTE_WH",
                  "snowflakeRole": "ACCOUNTADMIN"
                }
              }'      
        else    
            echo "Skipped!"
        fi
    - name: REST API with curl on manual trigger
      if: github.event_name == 'workflow_dispatch'
      run: |
          curl --request POST \
           --url https://app.coalescesoftware.io/scheduler/startRun \
           --header 'Authorization: Bearer AMf-vBwtq_HISM5lWO0ZrsjpZJUP8ZZyi6_ZvlW0TSJ1fP_B9G4gxJYedW1Dqn-BXWemry4R7U3Dz3898XP49_LhIW8Qky1FOx2w9N9klXHvKNxFO9VzXUPmuKR1GMCHg9rZEd2JisZjOUxJp0mDWbwha8EEqw6B9sPq_QxOxNKVGne7WOBMGsbZkKlkTTupvPmTcxmOZGaR6i3NE2-Y0TF0Y6ua_d_j6Q' \
           --header 'accept: application/json' \
           --header 'content-type: application/json' \
           --data '
            {
              "runDetails": {
                "parallelism": 16,
                "environmentID": "7"
              },
              "userCredentials": {
                "snowflakeAuthType": "Basic",
                "snowflakeUsername": "DEEPAK2899",
                "snowflakePassword": "DaDa2802#",
                "snowflakeWarehouse": "COMPUTE_WH",
                "snowflakeRole": "ACCOUNTADMIN"
              }
            }'    

        
